### Multiples of 3 and 5
* If we list all the natural numbers below 10 that are multiples of 3 and 5. We get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.

In [7]:
list = []

for i in range(1, 1000):
    if i%3 == 0 or i%5 == 0:
        list.append(i)
        
print(list)

[3, 5, 6, 9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35, 36, 39, 40, 42, 45, 48, 50, 51, 54, 55, 57, 60, 63, 65, 66, 69, 70, 72, 75, 78, 80, 81, 84, 85, 87, 90, 93, 95, 96, 99, 100, 102, 105, 108, 110, 111, 114, 115, 117, 120, 123, 125, 126, 129, 130, 132, 135, 138, 140, 141, 144, 145, 147, 150, 153, 155, 156, 159, 160, 162, 165, 168, 170, 171, 174, 175, 177, 180, 183, 185, 186, 189, 190, 192, 195, 198, 200, 201, 204, 205, 207, 210, 213, 215, 216, 219, 220, 222, 225, 228, 230, 231, 234, 235, 237, 240, 243, 245, 246, 249, 250, 252, 255, 258, 260, 261, 264, 265, 267, 270, 273, 275, 276, 279, 280, 282, 285, 288, 290, 291, 294, 295, 297, 300, 303, 305, 306, 309, 310, 312, 315, 318, 320, 321, 324, 325, 327, 330, 333, 335, 336, 339, 340, 342, 345, 348, 350, 351, 354, 355, 357, 360, 363, 365, 366, 369, 370, 372, 375, 378, 380, 381, 384, 385, 387, 390, 393, 395, 396, 399, 400, 402, 405, 408, 410, 411, 414, 415, 417, 420, 423, 425, 426, 429, 430, 432, 435, 438, 440, 441, 444, 445, 447, 450,

In [9]:
sum(list)

233168

### Self_Number
* d(n) = sum(n의자리수들) + n = generator. self number = not generator. for example 1, 3, 5, 7, 9, 20, 31...
* 1 to less than 5000. sum of self number???

In [1]:
def d(num):
    str_num = str(num)
    sum = 0
    for i in str_num:
        sum += int(i)
    return sum + num

In [2]:
d(91)

101

In [4]:
result_G = []

for i in range(1, 5000):
    result_G.append(d(i))
    G = result_G
    
print(G)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 99, 101, 103, 105, 107, 109, 111, 113, 115, 117, 101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 123, 125, 127, 129, 131, 133, 135, 137, 139, 141, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 167, 169, 171, 173, 175, 177, 179, 181, 183, 185, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 189, 191, 193, 195, 197, 199, 201, 203, 205, 207, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 213, 215, 217, 219, 221, 223, 225, 227, 229,

In [5]:
result_S = []

for j in range(1, 5000):
    if j not in G:
        result_S.append(j)
        
sum(result_S)

1227365

### Notice_paging
* Return all pages by entering the total number of posts and the number of posts.

In [31]:
def paging(m, n):
    page = m // n
    if m % n > 0:
        page += 1
    return page

In [32]:
paging(1, 10)

1

In [30]:
import pandas as pd

data = pd.DataFrame(columns={'m', 'n'}, data=[[0, 1], [1, 1], [2, 1], [1, 10], [10, 10], [11, 10]])
data

m   n
0   0   1
1   1   1
2   2   1
3   1  10
4  10  10
5  11  10

In [37]:
result = []

for i in range(6):
    data_paging = paging(data.loc[i]['m'], data.loc[i]['n'])
    result.append(data_paging)
    
print(result)
data['result'] = result
data

[0, 1, 2, 1, 1, 2]


m   n  result
0   0   1       0
1   1   1       1
2   2   1       2
3   1  10       1
4  10  10       1
5  11  10       2

### Eight_count
* How many total 8's from 1 to 10,000?
* Instead of counting the number of digits that contain 8, you must count all 8 digits.

In [43]:
str(list(range(1, 10000))).count('8')

4000

### Distance_pair
* Given a one-dimensional point, write a function that outputs a pair of the smallest of them.(Assume that all the arrays of endpoints are aligned.)

In [45]:
import numpy as np

points = np.random.randint(1, 1000, size=10)
points.sort()
points

array([201, 220, 402, 441, 456, 500, 785, 805, 936, 973])

In [48]:
ds = []

for i in range(len(points)-1):
    first = points[i]
    second = points[i+1]
    
    distance = abs(first - second)

    ds.append(distance)
    
    if min(ds) == distance:
        d = [first, second]
        
print(points)
print(ds)
print(d)

[201 220 402 441 456 500 785 805 936 973]
[19, 182, 39, 15, 44, 285, 20, 131, 37]
[441, 456]


### 1~1000_count_sum

In [62]:
list(range(1, 1001))

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185

In [63]:
str(list(range(1, 1001)))

'[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 2

In [66]:
result = []

for i in range(10):
    a = str(list(range(1, 1001))).count(str(i))
    result.append(a)
    
result

[192, 301, 300, 300, 300, 300, 300, 300, 300, 300]

### 10~1000_multiplied_sum

In [72]:
result_sum = []

for i in range(10, 1001):
    sp = list(str(i))
    sp_m = "*".join(sp)
    result_sum.append(eval(sp_m))
    
sum(result_sum)

93150

### Change Tab to Space
* Write program that change Tab to 4 space
----------------------------------------
* with open에서 파일의 인코딩을 확인

In [17]:
import os
import re

filepath = input('Enther path where file is located : ')
ext = input("Enter the extension : ")

Enther path where file is located : C:\Users\user\PycharmProjects\19tensor\Smart_Farm\Tomato
Enter the extension : py


In [23]:
_filelist = []

for cur, dirs, files in os.walk(filepath):
    for filenm in files:
        if (filenm.lower()).endswith(ext.lower()):
            _filelist.append(cur + "\\" + filenm)
    
print(_filelist)

['C:\\Users\\user\\PycharmProjects\\19tensor\\Smart_Farm\\Tomato\\Make_circle.py', 'C:\\Users\\user\\PycharmProjects\\19tensor\\Smart_Farm\\Tomato\\Seg_tomato.py']


In [42]:
for _path in _filelist:
    print(_path)
    os.system("copy {0} {1}".format(_path, _path+".txt"))

C:\Users\user\PycharmProjects\19tensor\Smart_Farm\Tomato\Make_circle.py
C:\Users\user\PycharmProjects\19tensor\Smart_Farm\Tomato\Seg_tomato.py


In [49]:
for _path in _filelist:
    with open(_path+".txt", 'r', encoding='UTF-8') as f:
        srcContent = f.read()
        with open(_path, 'w', encoding='UTF-8') as writelist:
            writelist.write(srcContent.replace("\t", "    "))

### Special_sort
* There is an array with n integers. After alignmnet, negative integers must be forward and positive integers must be backwards. Also, the order of positive integers and negative integers should be unchanged.

In [75]:
import numpy as np

ne_po_inte = np.random.randint(-100, 100, 20)
ne_po_inte

array([-25,   8,  71, -82,  88,  14,  99,  14, -90, -72,  61, -63,  -5,
       -13,  21,  29,  67,  54,  16,  11])

In [77]:
ne_list = []
po_list = []

for i in ne_po_inte:
    if i < 0:
        ne_list.append(i)
    else:
        po_list.append(i)
        
print(ne_list)
print(po_list)

[-25, -82, -90, -72, -63, -5, -13]
[8, 71, 88, 14, 99, 14, 61, 21, 29, 67, 54, 16, 11]


In [79]:
print(ne_list + po_list)

[-25, -82, -90, -72, -63, -5, -13, 8, 71, 88, 14, 99, 14, 61, 21, 29, 67, 54, 16, 11]


### Perfect_num
* The sum of all the quantities except for oneself is the natural number that becomes the self = Perfect number
* Outputs all perfect number less than N

In [143]:
N = int(input("Enter your number : "))

Enter your number : 10000


In [135]:
def d_ftn(N):
    l = []

    for i in range(1, N):
        if N % i == 0:
            l.append(int(i))

    if sum(l) == N:
        number=N
        print(N)
    else:
        print('Not perfect number')

In [137]:
d_ftn(27)

Not perfect number


In [142]:
result_p = []

for i in range(1, N+1):
    list_p = []
    
    for j in range(1, i):
        if i % j == 0:
            list_p.append(int(j))
            
    if sum(list_p) == i:
        result_p.append(i)
        
result_p

[6, 28, 496, 8128]

In [146]:
r = []

for i in range(1, N+1):
    sum = 0
    for j in range(1, i):
        if i % j == 0:
            sum += j
            
    if i == sum:
        r.append(i)
        
r

[6, 28, 496, 8128]